services:
  # Banco de dados MongoDB
  mongodb:
    image: mongo:7.0
    container_name: placaview-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ocr_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - placaview-network
    command: ["mongod", "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Backend FastAPI
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: placaview-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - DATABASE_NAME=ocr_db
      - COLLECTION_NAME=placas
      - UPLOAD_FOLDER=uploads
      - MAX_FILE_SIZE=52428800
    volumes:
      - ../backend:/app
      - ./uploads:/app/uploads
    depends_on:
      mongodb:
        condition: service_started
    restart: unless-stopped
    networks:
      - placaview-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Next.js
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: placaview-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
    networks:
      - placaview-network

  # Nginx (opcional - para produção)
  # nginx:
  #   image: nginx:alpine
  #   container_name: placaview-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - frontend
  #     - backend
  #   restart: unless-stopped
  #   networks:
  #     - placaview-network
  #   profiles:
  #     - production

volumes:
  mongodb_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  placaview-network:
    driver: bridge
